const router = require('express').Router();
const c = require('../controllers/classes.controller');
const { protect } = require('../middleware/auth.middleware');
const { authorize } = require('../middleware/role.middleware');
router.use(protect);
router.get('/',       c.getAll);
router.post('/',      authorize('admin'), c.create);
router.get('/:id',    c.getOne);
router.put('/:id',    authorize('admin'), c.update);
router.delete('/:id', authorize('admin'), c.remove);
module.exports = router;
